### PR TITLE
Remove collapsing of realizations in the convection_ratio CLI

### PR DESCRIPTION
**Pull request by gavinevans**
Description
This PR removes the automatic collapsing of realizations within the convective_ratio cube that is output from the convection_ratio CLI.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

### CODE REVIEW

**Review by bayliffe — APPROVED** [review]
I prefer a CLI that does less, so its a 👍 from me.

**Review by MoseleyS — APPROVED** [review]
I'm happy with this change. Adding a CellMethod to the threshold plugin is covered by epic IMPRO-1105.

**Review by MoseleyS — CHANGES_REQUESTED** [review]
Tests are not passing. I have merged Gavin's acceptance test data into master (in my datadir area) which fixed some tests, but still some failures:
= 16 failed, 2444 passed, 7 skipped, 2 xfailed, 477 warnings in 166.14 seconds =

**Comment by gavinevans** [comment]
@MoseleyS I've now rebased this branch and the acceptance test data following other changes to master.

The tests now pass => 2458 passed, 9 skipped, 2 xfailed, 498 warnings in 125.25 seconds

**Review by MoseleyS — APPROVED** [review]
Tests are now passing. Thanks Gavin.

**Pull request merged**
