### PR TITLE
Updating isort to version 5.x

### PR DESCRIPTION
**Pull request by BelligerG**
As the title says

Description

Testing:
 - [x] Ran tests and they passed OK

EDIT: Don't merge yet label added because we want: https://github.com/metoppv/improver/pull/1433 to go in first to avoid any possible conflicts

### CODE REVIEW

**Review by MoseleyS — DISMISSED** [review]

**Review by dmentipl — COMMENTED** [review]
This looks good. Although, I do wonder if we need to pin isort to a specific version at all now. I suppose it was pinned because there were breaking changes in isort at v5.0.0. Now that we are using a recent version, can we just leave it unpinned in `setup.cfg` and `environment_py37_iris24.yml`? Or pin it to version 5.* as opposed to a specific micro version of 5?

**Comment by BelligerG** [comment]
> This looks good. Although, I do wonder if we need to pin isort to a specific version at all now. I suppose it was pinned because there were breaking changes in isort at v5.0.0. Now that we are using a recent version, can we just leave it unpinned in `setup.cfg` and `environment_py37_iris24.yml`? Or pin it to version 5.* as opposed to a specific micro version of 5?

I'm happy to pin it to a 5.*, I'd rather not unpin it completely, just to avoid any ambiguity.

**Review by MoseleyS — APPROVED** [review]
I'm happy with this. If there's no reason to pin, then remove it until it is needed again.

**Review by dmentipl — APPROVED** [review]
All good. Pinning to 5.* is a reasonable compromise (as opposed to leaving it unpinned).

**Comment by MoseleyS** [comment]
I've checked that this doesn't cause conflicts in #1394  and #1433

**Pull request merged**
