### PR TITLE
Update high-level improver documentation on ReadTheDocs

### PR DESCRIPTION
**Pull request by gavinevans**
Related to https://github.com/metoppv/mo-blue-team/issues/787

This PR modifies some of the documentation on the improver ReadTheDocs site. The about.rst and frontpage.rst files have been updated to better reflect the current approach.

### CODE REVIEW

**Review by Kat-90 — DISMISSED** [review]
LGTM

**Review by brhooper — COMMENTED** [review]
Thanks @gavinevans. I've added a few comments suggesting minor changes.

**Review by brhooper — APPROVED** [review]
Thanks for making those changes @gavinevans, I'm happy to approve this now.

**Review by Kat-90 — APPROVED** [review]
Re-approving

**Pull request merged**
