### PR TITLE
Moved unit tests to reflect issue #90

### PR DESCRIPTION
**Pull request by bayliffe**
Issue #90 addressed to restructure unit tests. Module paths modified where necessary.

Testing:
 - [x] Ran tests and they passed OK

### CODE REVIEW

**Comment by fionaRust** [comment]
Blocked until after ECC ticket merged as it will need the same change to the unit test structure,

**Comment by gavinevans** [comment]
I think that there's now actually some redundancy in terms of the names of the tests, following the introduction of this more descriptive directory structure. For example, `test_ensemble_calibration_ContinuousRankedProbabilityScoreMinimisers.py` could be replaced by `test_ContinuousRankedProbabilityScoreMinimisers.py` without any loss of information, as the information is now in the directory structure.

**Comment by benfitzpatrick** [comment]
That makes sense @gavinevans

**Comment by bayliffe** [comment]
@TomekTrzeciak If we move the directory to the top level we will be contending with the bats tests, so should they then go into improver/tests/unit_tests?

**Comment by TomekTrzeciak** [comment]
@bayliffe Is there really a contention there? There is currently no ```tests/improver``` directory, and I don't think that bats will try to run python unit tests or vice versa.

Also, I think we better move the source of the bats framework out of the tests directory - ```mv tests/bin bats``` -
and merge the functions from ```tests/lib/util``` into ```bin/improver-tests``` (exporting them  into the environment with ```export -f``` - this way we won't have to source this file in every bats test that needs a function from there). This will leave only the actual tests under ```tests```. @benfitzpatrick Any thoughts on this?

**Comment by fionaRust** [comment]
I think we should be careful about keeping within the scope of the original ticket. This was originally just about pulling all the unit tests into one place. If we need to move lots of things around then I think that is out of scope of this ticket. (We can always do another ticket later.) I'm already worried that other people will have to change their code to move unit tests around once this is merged, and I'd prefer to limit the impact on other people.

**Comment by TomekTrzeciak** [comment]
@fionaRust If your concern is not to impact people more than necessary, then it makes even more sense to get it right the first time rather than have a follow on ticket. But the impact is only when we move the actual tests, moving bats code around won't impact anyone, so we can defer it for later if you wish (but then again, why wait with something so trivial).

**Comment by bayliffe** [comment]
I have removed redundant prefixes as @gavinevans suggested. After discussion, any further changes fall outside the scope of this ticket and will need to be addressed at a later date.

**Comment by bayliffe** [comment]
Replaced with PR #124 to resolve conflicts.

**Pull request closed without merging**
