### PR TITLE
github actions mamba error workaround

### PR DESCRIPTION
**Pull request by cpelley**
Applying the same change as @BelligerG made in https://github.com/MetOffice/improver_suite/pull/1282 to this repo.
That is to remove the json files under cache.

Additionally pinned 'click' to avoid issue with the version of black we are pinning, as per https://github.com/MetOffice/paraflow/pull/42

There is now a [recent version of black](https://github.com/psf/black/issues/2964) (>=22.3.0) which fixes/avoids the issue.  I tried updating black but this resulted in a number of formatting issues found by this more recent version of black.  Fixing these would be out of scope of this PR (updating black can be discussed in a separate issue).

## Background

- Removal of cache as per https://github.com/mamba-org/mamba/issues/488
- Pinning of 'click' (dependency of black) due to a failure of black (with the current pinned version of black we are using).  More info here: https://github.com/psf/black/issues/2964

### CODE REVIEW

**Review by s-boardman — COMMENTED** [review]
Fix for mamba consistent across workflows.

You're not using an environment cache in the `scheduled.yml` workflow?

**Comment by cpelley** [comment]
> You're not using an environment cache in the scheduled.yml workflow?

Good spot.  The workaround isn't necessary in that case for 'scheduled.yml' (I'll update now).
Not sure why cache isn't used here but I think beyond scope of this PR.

**Review by s-boardman — APPROVED** [review]

**Review by gavinevans — APPROVED** [review]
Thanks @cpelley 👍 

This looks fine to me.

**Comment by tjtg** [comment]
> You're not using an environment cache in the `scheduled.yml` workflow?

This is intentional - see https://github.com/metoppv/improver/pull/1651#issue-1108889073 for details.

**Pull request merged**
