### PR TITLE
Code coverage reporting for master

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This is aimed at #580.

This should add code coverage results to Codacy, at least for master (so we can view current and past coverage info). Incoming PRs from non-metoppv forks are hit by https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions and won't work with this.

Follows https://support.codacy.com/hc/en-us/articles/207279819-Coverage and https://github.com/codacy/python-codacy-coverage#setup.

I've added the token to our Travis setup, suitably securely: https://travis-ci.org/metoppv/improver/builds/386636363#L422

and the coverage uploads OK:
https://travis-ci.org/metoppv/improver/builds/386636363#L1987

### CODE REVIEW

**Comment by LaurenceBeard** [comment]
Looks good to me. 👍 

Test coverage reports will be useful.
I'm not certain not having it for individual PRs is a particular problem. I think it's a statistic we want to track on a larger scale, and some small parts of the code may not be suitable.

I can't see if this will give us other coverage reports?
 eg. showing unused code, but this can always be added, if supported by codacy.
 http://coverage.readthedocs.io/en/latest/branch.html

**Comment by benfitzpatrick** [comment]
> Based on the description in https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions, if we want to test this without merging this into master, then that could be done by creating a feature branch in the metoppv repository and merging these changes into the feature branch, and then creating a pull request from the feature branch to master. I think this would mean that we could test these changes without merging into master, based on what's written in https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions. Having said that, the changes here look fine. What do you think?

We think alike! This is what I've done here - the source branch for this PR is coverage-codacy on metoppv/improver! I think it will only work properly once it is merged - at the moment Codacy says 
image

**Comment by benfitzpatrick** [comment]
@gavinevans and @LaurenceBeard, could we have a go/no-go on the review status?

**Comment by benfitzpatrick** [comment]
Looks happy, thanks everyone:

https://app.codacy.com/project/metoppv_tech/improver/dashboard
https://app.codacy.com/app/metoppv_tech/improver/files

**Pull request merged**
