### PR TITLE
Merge back 1.0.4 

### PR DESCRIPTION
**Pull request by benfitzpatrick**
Incorporates #1634: Adds model-id-attr to wxcode modal.

Merge without squashing

### CODE REVIEW

**Comment by MoseleyS** [comment]
I'm trying to sort this out, but it is confusing me at the moment...

**Comment by MoseleyS** [comment]
Conflicts resolved (by creating a merging branch of the acceptance test data, merging master into this branch and resolving the conflict by running `improver-tests recreate_checksums` and committing the result). 
The changed checksums match those committed in #1634

**Review by BelligerG — APPROVED** [review]
All tests pass

**Review by PaulAbernethy — APPROVED** [review]
Matches changes from hotfix branch. Acceptance tests work correctly.

**Pull request merged**
