### PR TITLE
Change conda dependency solver to libmamba-solver

### LINKED ISSUE #1339: Cache reset
The current method for resetting the cache in github is to alter an environment variable: https://github.com/metoppv/improver/pull/1334

This means that if a reset is required, a pull request must be merged for potentially no code changes. It would be much nicer if we could reset the cache without having to alter the yml file at all. Something along the lines of using a secret (as suggested by @tjtg), however, there is an issue with using secrets in workflows on PRs from forks (see https://github.com/metoppv/improver/pull/1334#issuecomment-697186980).

### PR DESCRIPTION
**Pull request by tjtg**
Recent actions using the latest environment have been failing - see [recent example of the scheduled run](https://github.com/metoppv/improver/actions/runs/3927180994/jobs/6713568771).

The CI job actions aren't currently failing on metoppv, but this is because they're [using existing caches](https://github.com/metoppv/improver/actions/runs/3912012569/jobs/6686099418#step:3:14). These CI jobs will also start to fail if the caches become stale and get regenerated. As an example, this happened on my [personal fork](https://github.com/tjtg/improver/actions/runs/3927383494/jobs/6713958567).

This failure seems to be due to the conda version packaged in the current version of the runner VM images from Github Actions not working with mamba. See actions/runner-images#6910 for details.

The proposed solution here is to change over from installing and using the mamba CLI, to installing libmamba-solver and setting it as the dependency solver for conda to use.

**Update:**
I went to bump the cache number and force caches to be regenerated after the changeover to libmamba-solver, but there is now a web interface to do this rather than needing to commit a change in the repository. See https://github.com/metoppv/improver/actions/caches and click on the bin icons.
This change fixes #1339.

Testing:
 - [x] Ran tests and they passed OK

### CODE REVIEW

**Comment by tjtg** [comment]
Another way around this problem could be to change over to [conda-libmamba-solver](https://conda.github.io/conda-libmamba-solver/getting-started/) rather than installing and using the mamba CLI.

**Review by cpelley — COMMENTED** [review]
We just switched to [conda-libmamba-solver](https://conda.github.io/conda-libmamba-solver/getting-started/) for the improver_suite after hitting this issue and it seems stage has too.

I see your comment, you think it worth changing to that here too now?

**Comment by tjtg** [comment]
I'm happy to switch to libmamba solver now - looks like it's the preferred solution.

**Comment by tjtg** [comment]
I went to bump the cache number and force caches to be regenerated after the changeover to libmamba-solver, but there is now a web interface to do this rather than needing to commit a change in the repository. See https://github.com/metoppv/improver/actions/caches and click on the bin icons.

This change fixes #1334.

**Review by dmentipl — APPROVED** [review]
Thanks @tjtg for this. I've compared the changes against the already approved PR for the suite and the changes look good. Removing the manual changes to the cache using GitHub's new cache reset feature is a nice addition too.

**Comment by cpelley** [comment]
> ...there is now a web interface to do this rather than needing to commit a change in the repository...

Oooh finally!
Good spotting :)

**Review by cpelley — APPROVED** [review]
Thanks for sorting this @tjtg

**Comment by cpelley** [comment]
Given that CI is broken right now without this and we have PRs from the science team and two approvals here, I'm going to go ahead and merge.
Hope that's OK.
Thanks again @tjtg

**Pull request merged**
