### PR TITLE
Run tests in Github actions via singularity container

### PR DESCRIPTION
**Pull request by tjtg**
This PR adds a [Singularity container recipe](https://sylabs.io/guides/2.6/user-guide/) for IMPROVER and its dependencies, builds that container on Github actions and uses the container to run the test suite.

The container build is [cached](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows) so that it will not need to be rebuilt for each test run, unless the Singularity or Conda configuration is changed. The tests are run in parallel using multiple Github actions jobs, so that the total time to complete the test suite is reduced.

The singularity container is intended as a way for contributors to easily set up an environment for running IMPROVER, which will help address issues #883 and #888. It would still be nice to make IMPROVER installable as a package via pip and/or conda in the future.
As the singularity container is used for running the test suite, if there are issues with missing dependencies in the conda `environment.yml` or the Singularity container, this should be quickly noticed and fixed.

Testing:
 - [x] Ran tests and they passed OK

### CODE REVIEW

**Comment by tjtg** [comment]
The job matrix method you've used in tjtg/improver#1 cuts out a lot of repetition and is much nicer than what I did in this PR - thanks @TomekTrzeciak.

Regarding the caching, it would be good to include .github/workflow/tests.yml in the checksums used to form the cache key, so that editing this file also causes the container image to be rebuilt.

I'm going to be away for a few days but will pick up work on this again when I'm back.

**Comment by LaurenceBeard** [comment]
Thanks Tom.
 This is very similar to my attempt last month, but I was caching the conda env dir, rather than a container. Any benefits to a container instead?
 
 I was hitting the actions cache size limit - it was over 400MB limit, therefore not saving.
I can't see how the splitting of the container has resolved this.. as it is the total cache size - the tar.gz that it tries to cache, is still >400MB? *confused*

**Comment by LaurenceBeard** [comment]
I see, they have removed the 400MB single file limit, since my last attempt.
So there is no need to split the image before caching?

**Comment by LaurenceBeard** [comment]
I've stuck the conda caching example in PR #1138 for discussion. ^

**Comment by TomekTrzeciak** [comment]
> I see, they have removed the 400MB single file limit, since my last attempt.
> So there is no need to split the image before caching?

I've removed the splitting in tjtg/improver#1 and it seems to run fine.

Another thought: actions seems to have built-in support for docker, are there any advantages to it over singularity solution?

**Comment by tjtg** [comment]
After discussion with @benfitzpatrick, @LaurenceBeard, @TomekTrzeciak and @neilCrosswaite, the decision is to run the test suite on push and PR via a cached conda environment. This is the quickest and simplest method for general test running.

The singularity recipe in this PR/branch is still useful and should also be maintained as an option for running IMPROVER, particularly for external contributors outside the Met Office. Running the test suite inside a container helps enforce that there are no other dependencies or interactions with other software, as the default Github actions VM images contain a [large amount of pre-installed software](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts).
The singularity build and run doesn't need to be tested as often, so this could be done via a [scheduled](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onschedule) daily run.

We should go ahead with reviewing/merging #1138. The job matrix in https://github.com/tjtg/improver/pull/1 may also be useful there to reduce duplication.
I'll close this PR and work on another PR with the agreed usage of singularity.

**Pull request closed without merging**
