### PR TITLE
IMPRO-1875: Modify UK weather symbol decision tree to use cloud texture field

### PR DESCRIPTION
**Pull request by bayliffe**
Implements the decision tree tested in the preceding notebook for the UK models. This replaces cloud fraction with cloud texture at nodes that differentiate between continuous and showery precipitation.

(Still updating test data)

Testing:
 - [ ] Ran tests and they passed OK
 - [ ] Added new tests for the new feature(s)

### CODE REVIEW

**Comment by benfitzpatrick** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- improver_tests/wxcode/wxcode/test_WeatherSymbols.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6269591&bid=20410412)

**Review by gavinevans — APPROVED** [review]
Thanks for these changes, @bayliffe 👍 

These seem fine to me.

**Review by fionaRust — APPROVED** [review]
Looks good. Thanks Ben 🐳

**Comment by bayliffe** [comment]
@fionaRust are you saying it's whale-y good?

**Pull request merged**
