### PR TITLE
Allow environment variables in Rainforests config

### PR DESCRIPTION
**Pull request by nivnac**
Addresses #2046 

Rainforests config files contain a list of paths to the individual Treelite or LightGBM files.
This change adds parsing of these strings for environment variables using os.path.expandvars.

Testing:
 - [x] Ran tests and they passed OK

### CODE REVIEW

**Review by dmentipl — COMMENTED** [review]
Thanks @nivnac, these changes make sense in light of https://github.com/metoppv/improver/pull/2052. However, I see that you need to resolve merge conflicts.

**Review by dmentipl — COMMENTED** [review]
There seems to be a possible missing os.path.expandvars on line 199.

**Comment by nivnac** [comment]
> There seems to be a possible missing os.path.expandvars on line 199.

That is in check_filenames. That line also does not have the `expanduser()` part. I think that contrary to the docstring, this function is just checking that filenames are defined in the json dict rather than trying to parse it and confirm that files actually exist. And therefore a change isn't needed here. Maybe @benowen-bom or @btrotta-bom can confirm?

**Comment by dmentipl** [comment]
> That is in check_filenames. That line also does not have the `expanduser()` part. I think that contrary to the docstring, this function is just checking that filenames are defined in the json dict rather than trying to parse it and confirm that files actually exist. And therefore a change isn't needed here. Maybe @benowen-bom or @btrotta-bom can confirm?

Yes, that seems to be the case. Thanks for explaining.

**Review by dmentipl — APPROVED** [review]

**Pull request merged**
