### PR TITLE
Updating timezone cli call

### PR DESCRIPTION
**Pull request by BelligerG**
The CLIs for improver generally have the ancil files loaded as the last file. This updates the CLI to match the others within the suite.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

### CODE REVIEW

**Review by tjtg — DISMISSED** [review]
Changes to re-order arguments for better consistency with other CLIs make sense. We're not currently using this CLI at BOM, so this change won't have any impact on our suites.

**Comment by BelligerG** [comment]
This has become a bit of a hacky fix, to make this more robust in the future we should consider altering the interface as per https://github.com/metoppv/improver/issues/1553

**Review by Kat-90 — APPROVED** [review]
All looks good to me.

**Comment by benfitzpatrick** [comment]
No acceptance tests for this CLI in master, although we should consider it.

**Review by benfitzpatrick — APPROVED** [review]
Looks fine, works for the suite with the corresponding suite PR.

**Pull request merged**
