### PR TITLE
Spot-extraction additional coordinates ordering fix

### PR DESCRIPTION
**Pull request by bayliffe**
A small bug has existed in spot_extraction for a long time relating to the handling of additional leading dimensions. These additional dimensions were identified by flipping the order and indexing from 2 onwards to exclude spatial dimensions. If there is only one extra dimension this works fine, but for more than one the use of the np.flip means that the dimensions are in reversed order relative to the source cube, causing issues.

This tiny change just uses indexing relative to the end of the array to exclude the spatial dimensions and preserve the order.

Acceptance test added (branch): spot_extract_coord_fix

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

### CODE REVIEW

**Comment by cpelley** [comment]
Thanks @bayliffe.  In the general case I would use `​coord.coord_dims`​ for dimension mapping information since its quite possible to have more than one aux coord mapped to a dimension, or not have a dimension coordinate mapped to one or more dimensions at all etc.  As it stands, if I understand correctly, the code currently assumes each maps to a dimension in order

https://github.com/metoppv/improver/blob/c35f24333c7dcf8e6b16dc5f75d50ac0b34a4a8c/improver/spotdata/build_spotdata_cube.py#L181-L184

It's quite possible that inputs we deal with don't need to meet strict metadata checks that I am concerned with though, so please do feel free to disregard if you think I'm overly worrying??

**Comment by bayliffe** [comment]
@cpelley the auxiliary coordinates on spot-data outputs are always associated with the site-index coordinate. This is because (at least so far) the additional properties correspond to the site; these outputs contain no spatial grid, only the leading coordinates such as threshold or percentile. There are several of these aux-coords associated with the spot-index coordinate (rather than being limited to just one).

This code does handle coords that do not map to a dimension; these must be scalar and are added as scalars to the resulting spot output.

We could certainly revisit this to make it more robust, but ideally not as part of this small bug fix.

**Comment by cpelley** [comment]
> We could certainly revisit this to make it more robust, but ideally not as part of this small bug fix.

Thank you for your reply.
Fair enough :) agreed.

**Review by cpelley — APPROVED** [review]
Looks good to me.

Can you confirm how we normally manage changes to the acceptance test input files.  I assume you will merge your acceptance test data branch `spot_extract_coord_fix` into master of ppdev before merging this PR?

Cheers

**Comment by cpelley** [comment]
Thanks Ben.  Are you happy to merge or do you prefer an additional reviewer?

**Pull request merged**
