### PR TITLE
Use setuptools_scm to automatically obtain version

### PR DESCRIPTION
**Pull request by lucyleeow**
Use `setuptools_scm` to automatically get version from git tags (as suggested by/discussed with Tom & Tomek).

Description

Testing:
 - [N/A] Ran tests and they passed OK
 - [N/A] Added new tests for the new feature(s)

CLA
 - [N/A] If a new developer, signed up to CLA

### CODE REVIEW

**Comment by lucyleeow** [comment]
cc @tjtg @dmentipl

**Review by tjtg — APPROVED** [review]
Changes here all look OK and this is a nicer approach than having to put up PRs to bump a version number embedded in code or config files.

I've tested by creating a git version tag in my local workspace, then building a wheel `python setup.py bdist_wheel`, pip installing that wheel and `improver.__version` reports a version matching the tag from my workspace.

**Review by dmentipl — APPROVED** [review]
Looks good to me. I've tested similarly to Tom.

**Comment by lucyleeow** [comment]
Thanks @tjtg and @dmentipl !

**Pull request merged**
