### PR TITLE
MOBT-494: Modify day night mask to work with spot data.

### PR DESCRIPTION
**Pull request by bayliffe**
The day night mask plugin assumes a 2-D spatial grid at present. This PR modifies the plugin to work with an irregular grid defined with latitude and longitude coordinates, such as is found in spot data.

Unit test have been added.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

### CODE REVIEW

**Review by Katie-Howard — APPROVED** [review]
I've checked all the changes and they all seem sensible, and do what they are supposed to. I've run the tests and they are all working too, so I'm happy with these changes 👍

**Review by brhooper — COMMENTED** [review]
This all looks fine, my only question is regarding acceptance test good practice.

Whilst this PR doesn't alter any CLIs directly, the `apply_night_mask` CLI has had its functionality extended to handle spot data through these changes. In such cases, should an acceptance test be added to demonstrate this new behaviour, or are the new unit tests considered sufficient?

**Comment by bayliffe** [comment]
@brhooper in this case, as the unit tests cover the functionality quite well, I think we can get away without additional acceptance tests, but I am taking the path of least work for myself and my opinion is therefore skewed. Feel free to insist.

**Comment by brhooper** [comment]
> @brhooper in this case, as the unit tests cover the functionality quite well, I think we can get away without additional acceptance tests, but I am taking the path of least work for myself and my opinion is therefore skewed. Feel free to insist.

That's good enough for me, I agree that the unit tests cover the new functionality well.

**Review by brhooper — APPROVED** [review]

**Pull request merged**
