### PR TITLE
IMPRO-2082: Removes percentiles-to-probabilities CLI and plugin

### PR DESCRIPTION
**Pull request by MoseleyS**
Removes
- percentiles-to-probabilities CLI
- ProbabilitiesFromPercentiles2D Plugin
- Associated unit tests, acceptance tests and data

These are no longer required in the Met Office and are no longer supported.

Testing:
 - [x] Ran tests and they passed OK

### CODE REVIEW

**Comment by benfitzpatrick** [comment]
@MoseleyS, what about when we start to blend in percentile space but still require probability output at Level 3?

**Comment by MoseleyS** [comment]
> @MoseleyS, what about when we start to blend in percentile space but still require probability output at Level 3?

Hi Ben. We've talked about this, but it isn't in our plan at all. We don't really maintain code we aren't using so I think it should be removed. When we decide we want this functionality, we can resurrect it. I'm happy to be convinced otherwise.

**Review by gavinevans — APPROVED** [review]
This looks fine to me. Thanks @MoseleyS 👍

**Comment by benfitzpatrick** [comment]
OK, fair enough, it exists in the code base history!

**Review by Katie-Howard — CHANGES_REQUESTED** [review]
I've looked through all the files that you have deleted and they seem sensible. The unit tests all still run fine. However, when I ran the unit acceptance tests (even with your data), the checksums failed. The reason it gives is below:

    @pytest.mark.checksum
    def test_kgo_checksums():
        """Bulk check of all KGO checksums independent of other tests"""
        kgo_root = acc.kgo_root()
        data_paths = []
        # walk the KGO directory and gather all files and symlinks to files
        for directory, subdirectories, filenames in os.walk(kgo_root, topdown=True):
            # exclude dotfiles such as .git
            subdirectories[:] = [d for d in subdirectories if not d.startswith(".")]
            filenames = [f for f in filenames if not f.startswith(".")]
            for filename in filenames:
                data_paths.append(pathlib.Path(directory) / filename)
        try:
            # check that all the data files are in the list
>           assert len(data_paths) == len(acc.acceptance_checksums())
E           assert 600 == 597
E             -600
E             +597

improver_tests/acceptance/test_checksums.py:57: AssertionError
= 1 failed, 284 passed, 5 skipped, 2310 deselected, 2 xfailed, 146 warnings in 1024.06 seconds =


I also did a search in the IMPROVER directory for percentiles_to_probabilities and statistical_operations and the following files came up. So I'm not sure if these need to be deleted or altered to take out references to them. It would be good to check this. They mostly seem to be in improver/doc:

- improver/doc/build/html/improver.utilities.html (refers to statistical_operations)
- improver/doc/build/html/_sources/improver.cli.rst.txt (refers to percentiles_to_probabilities)
- improver/doc/build/html/improver.cli.percentiles_to_probabilities.html (this seems like it could be deleted?)
- improver/doc/build/html/improver.html (refers to both percentiles_to_probabilities and statistical_operations)
- doc/build/html/genindex.html (refers to  both percentiles_to_probabilities and statistical_operations)
- improver/doc/build/html/py-modindex.html (refers to  both percentiles_to_probabilities and statistical_operations)
- improver/doc/build/html/_sources/improever.cli.percentiles_to_probabilities.rst.txt (this could probably be deleted?)
- improver/doc/source/improver.cli.rst (refers to percentiles_to_probabilities)
- improver/doc/source/improver.cli.percentiles_to_probabilities.rst (this could be deleted?)
- improver/lib/coverage.xml (this refers to statistical_operations)
- improver/doc/build/html/improver.utilities.temporal.html (refers to statistical_operations)
- improver/doc/build/html/improver.utilities.statistical_operations.html (could this be deleted?)
- improver/doc/build/html/improver.utilities.spatial.html (this refers to statistical_operations)
- improver/doc/build/html/improver.utilities.html (this refers to statistical_operations)
- improver/doc/source/improver.utilities.statistical_operations.rst (this could be deleted?)
- improver/doc/source/improver.utilities.rst (this refers to statistical operations)
- improver/doc/build/html/_modules/improver/utilities/statistical_operations.html (this could be deleted?)

**Comment by MoseleyS** [comment]
I've merged recent updates on master into this branch (and for the acceptance test data too). The tests all pass again now.

**Review by Katie-Howard — APPROVED** [review]
I have spoken to Stephen about this work and also rerun the tests which pass now. So I'm happy that it all looks good 👍

**Pull request merged**
