### PR TITLE
ENH: spot-extract support generating time varying output

### PR DESCRIPTION
**Pull request by cpelley**
Addresses #1606

Description

Support providing more than one diagnostic file to the spot-extract, producing time varying output.

Testing:
 - [x] Ran tests and they passed OK

### CODE REVIEW

**Comment by cpelley** [comment]
I can explore adding a new acceptance test if desired? - let's see how this does in the suite first though.
Right now this PR naively loops over the input filepaths (cubes) provided to process each one individually.  This should address the issues identified in https://github.com/metoppv/improver/issues/1606: time spent saving the NetCDF (just onece for many input files) and time spent doing imports (again many files processed within 1 session).

Ideally we would make this a vectorised implementation, processing a single cube which varies with time - unfortunately the current spot extraction code makes assumptions about dimension mapping that would require a significant refactor.
I have down-prioritised that effort as we should see large benefit without.

**Comment by cpelley** [comment]
I'll start looking at improver-suite changes to utilise this first thing tomorrow - @BelligerG you might expect me to bother you! :)

**Review by BelligerG — COMMENTED** [review]
I did a quick test using 3 files:

- separate spot extract: 19s
- combined 6s

However, I did come across a few caveats that are worth discussing offline, namely mismatching metadata causing the `merge_cubes` to fail.

**Comment by cpelley** [comment]
I hadn't considered needing to combine calls each with lapse rate.
I'll fetch more data and test

**Comment by cpelley** [comment]
I have pushed up a change to support outputting to separate files (comma separated).
I'll update the tests if we confirm this is the UI is desired

**Comment by cpelley** [comment]
This was put on hold:
- Spot extract performance became a lesser issue.
- This PR requires a significant change in improver CLI to get the desired performance gains.

Leaving on hold for now.

**Comment by LaurenceBeard** [comment]
This would be nice to do, but python execution should remove much of this burden

**Comment by bayliffe** [comment]
Not being implemented at this time.

**Pull request closed without merging**
