### PR TITLE
Shrink acceptance test data - PR3

### PR DESCRIPTION
**Pull request by bayliffe**
A component of #1804

To reduce the data volume of the acceptance test data repository, work has been done to coarsen the resolution of test data relating to the following CLIs:

- combine
- wind-gust-diagnostic
- resolve-wind-components
- temporal-interpolate
- generate-percentiles

This PR updates the checksums.
The relevant acceptance test data can be found in branch `shrink_atd_3`
Plotting of the original and modified data [can be seen here](https://github.com/MetOffice/improver_aux/blob/acceptance_test_data_shrinking/notebooks/acceptance_test_data/shrink_atd_3.ipynb).

### CODE REVIEW

**Review by mspelman07 — DISMISSED** [review]
Happy to approve this. There is a conflict with master that'll need to be resolved before merging but given the number of changes being made to the acceptance test data it seems reasonable for this to be resolvedcloser to it being merged

**Review by MoseleyS — CHANGES_REQUESTED** [review]
`combine/broadcast/input_smaller_cube.nc` has got larger, not smaller. The number of grid points has dropped from 51 x 51 to 26 x 26, but I suspect something has been lost in terms of compression. There is no `"least_significant_digit"` attribute here. My instinct is that this particular test has already been shrunk and should not be changed again here.

`combine/multiplication/cell_methods` is also changing from small to slightly smaller. I'm willing to accept this one though.

**Comment by bayliffe** [comment]
@MoseleyS I've reset the broadcast test data back to the original state. I've updated the plotting, this PR, and the acceptance test data branch.

**Review by MoseleyS — APPROVED** [review]
Approved, but the conflicts need resolving.

**Review by mspelman07 — APPROVED** [review]

**Pull request merged**
