### PR TITLE
Field texture bug: Incorrect threshold being used

### PR DESCRIPTION
**Pull request by bayliffe**
The incorrect threshold is being used in the final thresholding step. Instead of using the textural threshold, the diagnostic threshold is being used. This means the textural threshold was being used no where. This PR corrects this mistake.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

### CODE REVIEW

**Review by fionaRust — COMMENTED** [review]
Should I be concerned that no unit tests were modified by this change?

**Comment by bayliffe** [comment]
@fionaRust probably. I'll take a look.

**Comment by bayliffe** [comment]
@fionaRust I have parameterised over the textural threshold in a test of process. The chosen thresholds span across the ratio values returned by the test data, whilst the previously incorrectly used diagnostic threshold does not. This test demonstrates that the textural threshold is being used and has an impact on the results.

**Review by fionaRust — COMMENTED** [review]
Also getting a checksum error when running the tests

**Comment by benfitzpatrick** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- improver_tests/field_texture/test_field_texture.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6222804&bid=20283099)

**Review by fionaRust — DISMISSED** [review]

**Review by fionaRust — APPROVED** [review]

**Comment by benfitzpatrick** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- improver_tests/field_texture/test_FieldTexture.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/metoppv_tech/improver/pullRequest?prid=6222804&bid=20283099)

**Review by cgsandford — APPROVED** [review]
This all makes sense and looks fine to me.

**Pull request merged**
