### PR TITLE
Mobt 157 nbhood refactor simplify  calculate neighbourhood

### PR DESCRIPTION
**Pull request by fionaRust**
A small extra tidy up of a neighbourhood processing method following Gavin's review comments on https://github.com/metoppv/improver/pull/1664

Testing:
 - [ ] Ran tests and they passed OK
 - [ ] Added new tests for the new feature(s)

CLA
 - [ ] If a new developer, signed up to CLA

### CODE REVIEW

**Review by gavinevans — APPROVED** [review]
Thanks @fionaRust 👍 

I think that this removes some redundant code and aids clarity.

**Review by Kat-90 — COMMENTED** [review]
Read through the code and run the tests. 

I noticed that there is a square_kernel directory in improver_tests that now has nothing in it, does that directory need deleting or is that being done somewhere else?

**Comment by fionaRust** [comment]
@Kat-90 Once all these PRs are done, I intend to do a final PR to put all the code in sensible name files and move the tests accordingly. I'll make sure I get rid of any empty test directories at that point.

**Review by Kat-90 — APPROVED** [review]
Thanks for the clarification.
Happy to approve.

**Pull request merged**
