### PR TITLE
Add security checks

### PR DESCRIPTION
**Pull request by dmentipl**
Addresses #1382 

Run bandit and safety as part of CI. Bandit finds common security issues in Python code. Safety checks installed dependencies for know security vulnerabilities. 

If bandit/safety find any issues the tests will _not_ fail. However, the output is written to the log (in GitHub Actions) for inspection.

Testing:
 - [x] Ran tests and they passed OK
 - [x] Added new tests for the new feature(s)

CLA
 - [x] If a new developer, signed up to CLA

### CODE REVIEW

**Review by tjtg — APPROVED** [review]
All looks good. 
Bandit has found a few assert statements in non-test code. I'll create another issue to tackle those.

**Comment by benfitzpatrick** [comment]
Thank you @dmentipl! Looks good. I'm half wondering if bandit should just fail - what do you think?

**Comment by dmentipl** [comment]
No worries, @benfitzpatrick!

We certainly could fail with bandit. However, it does pick up things like using assert, which is a low severity issue. We could add the `-ll` flag which reports on "medium" severity and higher, e.g. ignoring use of assert.

What do you and @tjtg think?

**Comment by tjtg** [comment]
> I'm half wondering if bandit should just fail - what do you think?

We should make it so that bandit fails if it identifies issues, but not right now.
There are a few existing issues identified by bandit (see #1386) and those existing issues would cause all CI jobs to be marked as failing until they get addressed. The flags to only fail on medium or high severity issues won't help here as one of the currently identified issues is high severity.

**Pull request merged**
